export const districts = [
    {
        name: "Thiruvananthapuram",
        desc: "Thiruvananthapuram (or Trivandrum) is the capital of the southern Indian state of Kerala. . ",
        Image:"https://keralatravels.com/userfiles/1474446260__1341.jpeg",
        content:"Thiruvananthapuram (formerly known as Trivandrum) is the capital city of the Indian state of Kerala. It is located on the southwestern coast of India, along the Arabian Sea. Thiruvananthapuram is known for its rich cultural heritage, as well as its natural beauty. It has many historic temples, museums, and palaces, as well as beautiful beaches and backwaters. Some of the popular tourist attractions in Thiruvananthapuram include the Padmanabhaswamy Temple, the Kuthiramalika Palace Museum, the Napier Museum, the Zoological Park, and the beaches at Kovalam, Varkala, and Shankumugham. Thiruvananthapuram is also a hub for technology and education, with many prestigious universities and research centers located in the city. It has a vibrant economy, driven by industries such as tourism, software development, and healthcare. The city has a tropical climate, with hot and humid summers and mild winters. The best time to visit Thiruvananthapuram is during the winter months (November to February), when the weather is pleasant and dry."
    },
    {
        name: "Kollam",
        desc: "Kollam is a city in the state of Kerala, on India's Malabar Coast. It's known as a trade hub and for its beaches. . ",
        Image:"https://www.adameshandbook.com/wp-content/uploads/2020/01/jatayu-1.jpg",
        content:"Kollam, also known as Quilon, is a coastal city in the southern Indian state of Kerala. It is located about 70 kilometers north of the state capital, Thiruvananthapuram. Kollam is known for its scenic beauty, historic landmarks, and cultural heritage. The city has a rich history, dating back to the 9th century, and has been a major center of trade and commerce for centuries. Kollam was once an important port city and a major center for the spice trade. Some of the popular tourist attractions in Kollam include the Ashtamudi Lake, which is the second largest lake in Kerala and a popular destination for boating and water sports, the Thangassery Lighthouse, the Kollam Beach, and the Mahatma Gandhi Beach and Park. Kollam is also known for its traditional cashew nut processing industry and is a major exporter of cashews. The city is also home to several educational institutions, including the University of Kerala, as well as several hospitals and healthcare facilities. Kollam has a tropical climate, with hot and humid summers and mild winters. The best time to visit Kollam is between the months of October and March when the weather is relatively cooler and more pleasant."
    },
    {
        name: "Pathanamthitta",
        desc: "Pathanamthitta, is a municipality situated in the Central Travancore region in the state of Kerala ",
        Image:"https://dynamic-media-cdn.tripadvisor.com/media/photo-o/11/17/fb/80/perunthenaruvi-waterfall.jpg?w=700&h=-1&s=1",
        content:"Pathanamthitta is a district located in the southern Indian state of Kerala. It is situated in the central Travancore region of the state and is known for its scenic beauty, rich cultural heritage, and religious significance. The district has a population of around 1.2 million people and covers an area of approximately 2,634 square kilometers. Pathanamthitta is known for its numerous temples, including the famous Sabarimala Temple, which is one of the most visited pilgrimage sites in the world. Other popular attractions in the district include the Perunthenaruvi Waterfalls, the Pandalam Palace, and the Konni Elephant Training Center. The district is also home to several wildlife sanctuaries and national parks, such as the Periyar Tiger Reserve and the Pampa River Sanctuary. The economy of Pathanamthitta is primarily driven by agriculture, with rubber, coconut, and pepper being the main crops. The district also has a thriving tourism industry, thanks to its natural beauty and cultural heritage."
    },
    {
        name: "Alappuzha",
        desc: "Alappuzha (or Alleppey) is a city on the Laccadive Sea in the southern Indian state of Kerala. . ",
        Image:"https://s3.india.com/travel/wp-content/uploads/2017/05/Alleppey.jpg",
        content:"Alappuzha, also known as Alleppey, is a city in the southern Indian state of Kerala. It is located on the Arabian Sea coast and is known for its picturesque backwaters, beaches, canals, and lagoons. Alappuzha has a population of approximately 174,000 people and covers an area of 1,414 square kilometers. The backwaters of Alappuzha are one of the city's most popular attractions, and tourists come from all over the world to take a ride on a traditional houseboat and experience the serene beauty of the backwaters. The city is also known for its beaches, such as Marari Beach and Alappuzha Beach, which offer opportunities for swimming, sunbathing, and water sports. Alappuzha is a major center for coir production, and the city's economy is also driven by agriculture and tourism. The region is known for its production of rice, spices, and coconut. The city is also famous for the annual Nehru Trophy Boat Race, which takes place on the Punnamada Lake and is one of the most popular events in Kerala. In addition to its natural beauty and cultural significance, Alappuzha is also home to several historic landmarks, such as the St. Andrew's Basilica, the Krishnapuram Palace, and the Ambalappuzha Sri Krishna Temple. Overall, Alappuzha is a fascinating destination for travelers looking to experience the rich culture and natural beauty of Kerala."
    },
    {
        name: "Kottayam",
        desc: "Kottayam is a municipal town in the Indian state of Kerala.",
        Image:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Vembanad_Lake_at_Kumarakom.jpg/1920px-Vembanad_Lake_at_Kumarakom.jpg",
        content:"Kottayam is a city in the southern Indian state of Kerala. It is located in the central part of the state and is known for its rich cultural heritage, historic landmarks, and natural beauty. Kottayam has a population of approximately 136,000 people and covers an area of 57.4 square kilometers.Kottayam is known for its contributions to the fields of literature and journalism, and the city has been home to several prominent writers and journalists over the years. The city is also known for its educational institutions, including the Mahatma Gandhi University and the CMS College, which are among the oldest and most prestigious institutions in Kerala. Kottayam is surrounded by hills and waterfalls, and the region is known for its natural beauty. The city is also home to several historic landmarks, such as the Thirunakkara Mahadeva Temple, the St. Mary's Orthodox Church, and the Vimalagiri Cathedral. The city also has several museums, such as the Bay Island Driftwood Museum and the Kerala Folklore Museum, which showcase the region's rich cultural heritage. The economy of Kottayam is primarily driven by agriculture, with rubber, coconut, and spices being the main crops. The city is also home to several industries, such as printing and publishing, with several prominent publishing houses located in Kottayam. Overall, Kottayam is a fascinating destination for travelers looking to experience the culture, history, and natural beauty of Kerala."
    },
    {
        name: "Ernakulam",
        desc: "Sprawling, residential Ernakulam is known for Marine Drive, a busy waterfront promenade.  . ",
        Image:"https://spb.kerala.gov.in/sites/default/files/styles/inner_banner_image_850x460/public/2020-09/4_1.jpg?itok=QdkvH5Ma",
        content:"Ernakulam is a city in the southern Indian state of Kerala. It is located in the central part of the state and is the commercial capital of Kerala. Ernakulam has a population of approximately 650,000 people and covers an area of 94.88 square kilometers. Ernakulam is known for its bustling commercial center, with several shopping malls, markets, and businesses located in the city. The city is also home to several cultural landmarks, such as the Hill Palace Museum, the Cochin Marine Drive, and the Paradesi Synagogue. The Mattancherry Palace, also known as the Dutch Palace, is a popular tourist destination and is known for its beautiful murals and artifacts. Ernakulam is situated on the banks of the Vembanad Lake and is surrounded by several backwaters and lagoons. The region is known for its natural beauty, and tourists come from all over the world to experience the serene backwaters and beaches. The city is also home to several wildlife sanctuaries, such as the Thattekad Bird Sanctuary and the Chinnar Wildlife Sanctuary. The economy of Ernakulam is primarily driven by commerce and industry, with several major companies and businesses located in the city. The region is also known for its production of spices, coconuts, and rubber. The Kochi Port, located in Ernakulam, is one of the busiest ports in India and plays a vital role in the region's economy. Overall, Ernakulam is a fascinating destination for travelers looking to experience the commercial and cultural hub of Kerala, as well as the natural beauty of the region."
    },
    {
        name: "Palakkad",
        desc: "Palakkad, or Palghat, is a city in Kerala, a state in southwestern India. ",
        Image:"https://spb.kerala.gov.in/sites/default/files/styles/inner_banner_image_850x460/public/2020-09/palakkad.jpg?itok=Xd75QKHG",
        content:"Palakkad, also known as Palghat, is a city in the southern Indian state of Kerala. It is located on the border of Kerala and Tamil Nadu, and is known for its scenic beauty, historic landmarks, and cultural heritage. Palakkad has a population of approximately 131,000 people and covers an area of 26.60 square kilometers. Palakkad is surrounded by hills and forests, and the region is known for its natural beauty. The city is also home to several historic landmarks, such as the Palakkad Fort, which was built by Hyder Ali of Mysore in the 18th century, and the Jain Temple of Jainimedu, which is believed to be over 500 years old. Palakkad is known for its contributions to the fields of literature and music, and the city has been home to several prominent writers and musicians over the years. The city is also known for its traditional art forms, such as the Ottamthullal and Kathakali, which are performed during festivals and cultural events. The economy of Palakkad is primarily driven by agriculture, with rice, coconut, and banana being the main crops. The region is also known for its production of spices, such as black pepper and cardamom. The city is home to several small and medium-sized industries, such as textile mills and metal fabrication units. Overall, Palakkad is a fascinating destination for travelers looking to experience the natural beauty, historic landmarks, and cultural heritage of Kerala."
    },
    {
        name: "Kasaragod",
        desc: "Kasaragod is a municipal town and administrative headquarters of Kasaragod district in the state of Kerala ",
        Image:"https://www.keralatourism.org/images/destination/mobile/aquatourism_in_kasaragod20131107114603_306_1.jpg",
        content:"Kasaragod is a district located in the northernmost part of the southern Indian state of Kerala. It shares its borders with the neighboring states of Karnataka and the Arabian Sea. The district has a diverse population consisting of different religions, cultures, and languages, including Malayalam, Kannada, and Tulu. Kasaragod has a rich history and is known for its cultural heritage, natural beauty, and ancient temples. The district is home to several important tourist attractions, such as Bekal Fort, Ananthapura Lake Temple, Kappil Beach, and Chandragiri Fort. The economy of Kasaragod is mainly dependent on agriculture and fishing, and it is also known for its coir and handloom industries. The district is well-connected to other parts of Kerala and Karnataka through road and rail networks, and the nearest airport is Mangalore International Airport, which is located in the neighboring state of Karnataka."
    },
    {
        name: "Idukki",
        desc: "Idukki is a township in Idukki district near to the district headquarter Painavu in the state of Kerala ",
        Image:"https://keralatourism.travel/images/destinations/headers/idukki-kerala-tourism-entry-fee-timings-holidays-reviews-header.jpg",
        content:"Idukki is a district located in the southern Indian state of Kerala. It is situated in the Western Ghats, and is known for its beautiful landscapes, rich biodiversity, and tea and spice plantations. The district is also home to the Idukki Arch Dam, which is one of the highest arch dams in Asia and an important source of hydroelectric power. Idukki has a diverse population, consisting of people from different religions, cultures, and languages. The district is home to several indigenous communities, including the Muthuvan, Malapandaram, and Mannan tribes. Tourism is an important industry in Idukki, and the district is known for its natural beauty and wildlife. Some of the popular tourist attractions in Idukki include the hill stations of Munnar and Vagamon, the Periyar Wildlife Sanctuary, and the Anamudi Peak, which is the highest peak in South India. Agriculture is also an important sector in Idukki, and the district is known for its production of spices, such as cardamom, pepper, and cinnamon. Other important industries in the district include tea and coffee cultivation, and the production of handloom and handicrafts."
    },
    {
        name: "Thrissur",
        desc: "Thrissur is a city in the south Indian state of Kerala ",
        Image:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Kudamatom_at_thrissur_pooram_2013_7618.JPG/1920px-Kudamatom_at_thrissur_pooram_2013_7618.JPG",
        content:"Thrissur is a district located in the central part of the southern Indian state of Kerala. It is known as the cultural capital of Kerala due to its rich cultural heritage and historical significance. The district is also famous for its festivals, including the Thrissur Pooram, which is one of the largest and most spectacular festivals in Kerala. Thrissur has a diverse population consisting of people from different religions, cultures, and languages. The district is home to several important temples, including the Vadakkunnathan Temple, which is one of the oldest and most important Shiva temples in South India. Thrissur is also home to several churches and mosques, including the famous Our Lady of Dolours Basilica, which is a prominent Catholic church. Tourism is an important industry in Thrissur, and the district is known for its cultural and historical significance. Some of the popular tourist attractions in Thrissur include the Guruvayur Temple, Athirapally Waterfalls, and the Thrissur Zoo and Museum. Agriculture is an important sector in Thrissur, and the district is known for its production of paddy, coconut, and banana. Other important industries in the district include textile and garment manufacturing, and the production of handloom and handicrafts. Thrissur is also a hub for education and healthcare, with several universities and hospitals located in the district."
    },

    {
        name: "Malappuram",
        desc: "Malappuram is a city in the Indian state of Kerala, spread over an area of 58.20 km² ",
        Image:"https://www.keralatourism.org/images/enchanting_kerala/large/thirunavaya_malappuram20230105140626_1260_1.jpg",
        content:"Malappuram is a district located in the northern part of the southern Indian state of Kerala. It is the third-most populous district in Kerala and is known for its scenic beauty, cultural diversity, and historical significance. The district has a rich history and was an important center of trade and commerce in ancient times. Malappuram has a diverse population consisting of people from different religions, cultures, and languages. The district is home to several important mosques, including the Cheraman Juma Masjid, which is believed to be the first mosque in India. Malappuram is also known for its traditional art forms, such as Theyyam and Oppana, which are performed during religious festivals and other occasions. Tourism is an important industry in Malappuram, and the district is known for its natural beauty and historical significance. Some of the popular tourist attractions in Malappuram include the Kadalundi Bird Sanctuary, Thirunavaya Navamukunda Temple, and the Ponnani Harbor. Agriculture is the mainstay of the economy in Malappuram, and the district is known for its production of paddy, coconut, and banana. Other important industries in the district include textile and garment manufacturing, and the production of handloom and handicrafts. The district is also home to several educational institutions, including the University of Calicut, and several healthcare facilities."
    },
    {
        name: "Wayanad",
        desc: "Wayanad is a rural district in Kerala state, southwest India. In the east, the Wayanad Wildlife Sanctuary is a lush ",
        Image:"https://img.onmanorama.com/content/dam/mm/en/travel/kerala/images/2021/10/21/wayanad.jpg",
    },
    {
        name: "Kozhikode",
        desc: "Kozhikode is a coastal city in the south Indian state of Kerala. It was a significant spice trade center ",
        Image:"https://www.keralatourism.org/images/destination/mobile/kozhikode_beach20150811120557_256_1.jpg",
    },
    {
        name: "Kannur",
        desc: "Kannur is a coastal city in the south Indian state of Kerala. ",
        Image:"https://www.dtpckannur.com/public/img/inner/kannur.jpg",
    },
]
